spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB1
    user: danilmorozov
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml
      enable: true
